language: node_js
node_js:
- '10.12.0'
cache:
  directories:
  - node_modules
install:
- npm install
- npm rebuild --runtime=electron --target=2.0.10 --disturl=https://atom.io/download/electron
script:
- npm run lint
- npm test
- npm run build
