language: node_js
node_js:
- '10.12.0'
branches:
  only:
  - master
install:
- npm install
- npm rebuild --runtime=electron --target=2.0.10 --disturl=https://atom.io/download/electron
script:
- npm run lint
- npm run build
- npm test